### ISSUE TITLE
Investigte/Fix OOM Crashing of warden operator

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/warden#298]
**Description**

It looks like current implementation of warden operator crashes with OOM in case of high amount of workloads marked with verification failed

**AC**

 - [ ] in case there are multiple workloads labelled with verification=failed, the warden operator should not crash

**Comment by anoipm** [comment]
**Problem:**
The Warden operator takes up a lot of memory on one of the clusters. This causes it to occasionally exceed the available memory limit and be restarted after an OOM error.

**Suspicion:**
There is a memory leak in the component or the component allocates too much memory.

**Analysis:**
Many tests have shown that the component's memory usage appears to be stable. It fluctuates during the component's life but does not exceed a certain level. This means that we are probably not dealing with a memory leak.
Warden's memory consumption depends on the size of Kubernetes resources (mainly pods) on the cluster. The component monitors (using the cache mechanism) the status of pods from all namespaces and therefore keeps a copy of data from all pods in the cluster (not only from protected namespaces) in the cache.
The result of image verification (e.g. verification=failed) has no impact on memory usage and component restarts.

**Hypothetical possibilities and applied (or not) solutions to the problem:**
1) Increasing the limit of available memory.
We have almost doubled this limit to 300MiB.
2) Disabling the cache of resources downloaded from Kubernetes.
We have two controllers in the Warden operator component - for namespaces and pods. We do not have the option to disable this cache only for the namespace controller because it is necessary for the operation of the pod operator. Something to consider is a possible change to the Warden architecture so that the operator does not have a pod operator.
We are not considering such a change at the moment.
3) Paging download of pod list in namespace controller.
Paging could reduce the temporary memory usage when loading the entire list of pods from protected namespaces. However, paging does not make sense when we use a cache, because all the data in the cache is already stored.
This change doesn't make sense, so we don't do it.

**Possible minor improvements:**
1) Removed unnecessary copying of pod data objects in the namespace controller.
2) Label the operator so that Istio sidecar is not added to it.
